export const metadata = {
  title: "Ttasker",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="/icon.svg"
        type="image/svg+xml"
        sizes="any"
      />
      <body>{children}</body>
    </html>
  );
}
